### ISSUE TITLE
Make it work with Webpack 4

### ISSUE THREAD

**Issue by forepointmc** [GoogleChromeLabs/critters#12]
if (compilation.hooks.htmlWebpackPluginAfterHtmlProcessing) {

**Comment by developit** [comment]
Hmm - this already works with Webpack 4. Are you looking at master?
https://github.com/GoogleChromeLabs/critters/blob/c53df3d6b1f1b63b6374d79b0fa565c48e60a85f/src/index.js#L92

**Comment by koresar** [comment]
It works nicely. I have just tested.
