### ISSUE TITLE
How to use critters in next.js v13

### ISSUE THREAD

**Issue by yudiz-kandarp** [GoogleChromeLabs/critters#126]

**Comment by marco910** [comment]
1. Add `experimental: { optimizeCss: true }` to your `next.config.js`
2. Run `npm i -D critters` to install Critters.

That's it

**Comment by leerob** [comment]
Note for those landing here through search, Critters does not work with the App Router: https://github.com/vercel/next.js/discussions/59989#discussioncomment-7962270
