### ISSUE TITLE
Can this work with php/Wordpress themes?

### ISSUE THREAD

**Issue by jcklpe** [GoogleChromeLabs/critters#16]
Sorry to ask what may be a fairly obvious question but I'm a designer learning to code and so maybe this is a dumb question. 

I'm rebuilding a Wordpress theme and I want to use webpack to bundle my assets. So far that's all worked great. BUT, I was wondering if it would be feasible to use critters in this task? Normally with WP themes I have to do all my critical css inline manually and it's a huge pain the neck. I tried a first pass installation of Critters into my current theme's webpack config but when running npm build I get the "no html element detected" response, which makes sense because the html is being created via php on the server. But that doesn't stop other JS inclusions that pull html etc from other pages (such as swup or barbajs) from accessing the html so I'm curious if maybe there's something I'm missing in my configuration? 

Any thoughts?

**Comment by developit** [comment]
Seems like the best solution here would be to add a "placeholder" HTML file to your Webpack build (it could likely just be empty), and then grab the CSS from it once the build is completed. You could use `html-webpack-plugin` for this.

**Comment by jcklpe** [comment]
@developit  Thank you Jason. Yeah, I've basically decided to go with a backend solution for now, and use something like critters once I finally get around to decoupling my frontend and doing an SPA frontend etc which will run better with webpack type thinking. Thanks!
