### ISSUE TITLE
Maintain order of CSS

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChromeLabs/critters#17]
From https://github.com/GoogleChromeLabs/squoosh/pull/322.

In dev, the intro bundle appears first, followed by the main bundle.

After Critters, the intro bundle is inlined (as intended), but it's inserted *after* the main bundle.

This breaks CSS that depends on ordering.

**Comment by developit** [comment]
Yikes! Should be easy to fix.

**Comment by developit** [comment]
Ah - looks like this can be fixed by passing `mergeStylesheets:false`.

**Comment by developit** [comment]
Fixed in 607fc3f! Released as [2.2.1](https://github.com/GoogleChromeLabs/critters/releases/tag/2.1.1).
