### ISSUE TITLE
Always set crossorigin for font files

### ISSUE THREAD

**Issue by Ansimorph** [GoogleChromeLabs/critters#18]
I have `preloadFonts` set to `true`, resulting in a preload like this:

`<link rel="preload" as="font" href="CanelaDeck-Bold-Web.woff2"/>`

Even though this is not a cross-domain request this preload is discarded by Chrome:

> A preload for 'https://develop.mydomain.xyz/CanelaDeck-Bold-Web.woff2' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.

If I read https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content correctly the preload needs a `crossorigin="anonymous"` even if it is in the same domain.

**Comment by developit** [comment]
We should make `crossorigin="anonymous"` the default. It has no effect for same-origin resources anyway. PR's welcome!

**Comment by developit** [comment]
Whoops just re-read. I've opened a PR for the fix.

**Comment by Ansimorph** [comment]
Thanks so much! The PR solves the problem.
