### ISSUE TITLE
problem with Angular !!

### ISSUE THREAD

**Issue by aymenbz** [GoogleChromeLabs/critters#23]
i'm trying to use this plugin with Angular, it works but i'm getting an error 
`Uncaught Error: In this configuration Angular requires Zone.js`
and because of this error there is some features not working anymore.

and this is my code 
```
new HtmlWebpackPlugin({
      filename: 'index.html',
      template: './src/index.html',
      chunksSortMode: 'none',
    }),
    new Critters({
      pruneSource: false
    })
```
Does anyone have an example working with Angular ?
Thanks

**Comment by developit** [comment]
I don't think the error you're seeing has anything to do with Critters.
