### ISSUE TITLE
Get error 'textContent' of undefined

### ISSUE THREAD

**Issue by agusesetiyono** [GoogleChromeLabs/critters#24]
ERROR in   TypeError: Cannot read property 'textContent' of undefined
  
  - critters.js:225 Critters.<anonymous>
    [default]/[critters-webpack-plugin]/dist/critters.js:225:22
  
  - critters.js:220 Critters.mergeStylesheets
    [default]/[critters-webpack-plugin]/dist/critters.js:220:12
  
  - critters.js:197 Critters.<anonymous>
    [default]/[critters-webpack-plugin]/dist/critters.js:197:37

**Comment by developit** [comment]
Set `mergeStylesheets` to `false`:

```js
new Critters({
  mergeStylesheets: false
})
```

**Comment by developit** [comment]
Released in [2.1.3](https://github.com/GoogleChromeLabs/critters/releases/tag/2.1.3)
