### ISSUE TITLE
Cannot read property 'compilation' of undefined

### ISSUE THREAD

**Issue by koresar** [GoogleChromeLabs/critters#3]
I don't know what's going on here. Just reporting a bug.
```
⠋ building for production.../Users/vasyl/code/node_modules/critters-webpack-plugin/dist/critters.js:181
    compiler.hooks.compilation.tap(PLUGIN_NAME, function (compilation) {
                   ^

TypeError: Cannot read property 'compilation' of undefined
    at Critters.apply (/Users/vasyl/code/node_modules/critters-webpack-plugin/dist/critters.js:181:20)
    at Compiler.apply (/Users/vasyl/code/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/Users/vasyl/code/node_modules/webpack/lib/webpack.js:33:19)
    at err (/Users/vasyl/code/build/build.js:19:5)
...
```

Webpack 3. VueJS project. Happens regardless of where in the plugin array I add critters.

I am far from being the best frontend developer. Not familiar with how webpack works either.

**Comment by developit** [comment]
Ah - I think right now we require Webpack 4+, but it would be a simple change to support 3 and prior.

**Comment by Hazlank** [comment]
It can support webpack 3 now?Want to try it

**Comment by suhasdeshpande** [comment]
@developit What's the simple change? I could do it if I know how to do it. Love simple changes. :)

**Comment by catskull** [comment]
I've tried this using webpack 3 and 4 and the error is the same on both. I'm using https://github.com/rails/webpacker, but I've never had any issues with other webpack plugins. I'd love to be able to use this!

**Comment by OngeUK** [comment]
I'm getting the same error when using in conjunction with `preact-cli`.

**Comment by JakeHenshall** [comment]
Same issue using Laravel Mix WebpackConfig

```
mix.webpackConfig({
    plugins: [
        new Critters({
            // Outputs: <link rel="preload" onload="this.rel='stylesheet'">
            preload: 'swap',

            // Don't inline critical font-face rules, but preload the font URLs:
            preloadFonts: true
        })
    ],
});
```
