### ISSUE TITLE
How to inline Vue component's styles?

### ISSUE THREAD

**Issue by mdawar** [GoogleChromeLabs/critters#42]
Hi,
Thank you for this great project, I have a question please about inlining Vue component's styles, I'm not using Vue cli, I have a custom Webpack configuration for Vue and I'm using `mini-css-extract-plugin`, for the CSS I'm using an external stylesheet (Bulma) with a little bit of custom CSS for some Vue components, the thing is that **Critters** is working just fine for the external stylesheet but for the custom Vue component's CSS it's not, this is my **Critters** plugin config:

```js
new Critters({
  external: true,
  inlineThreshold: 15*1024,
  minimumExternalSize: 15*1024,
  pruneSource: true,
  compress: true,
  logLevel: 'info'
})
```

The external stylesheet is inlined but the component's CSS is not, even though their size is very small, is their anything that I can do to make **Critters** plugin process these CSS styles?

Thank you.

**Comment by atilkan** [comment]
Does your keyboard doesn't have a dot (.) ? 
Note; Above sign is not a boob it is dot inside parenthesis, here boobs -> ( . ) ( . )

**Comment by developit** [comment]
@mdawar can you post an example (simplified if possible) of what your Vue component looks like? It sounds like you're not pre-rendering your components to HTML, which means Critters can't know which styles to inline.

You might be able to use something like this to add prerendering to your webpack setup:
https://github.com/chrisvfritz/prerender-spa-plugin

**Comment by atilkan** [comment]
Dont you let a man a little fun.

**Comment by mdawar** [comment]
@developit I'm already using `prerender-spa-plugin`, I've created an example repo at https://github.com/mdawar/critters-vue-example

And I've found that using dynamic imports is causing this behavior, the `master` branch uses dynamic imports in `src/router.js` and the `regular-import` branch uses regular imports which makes Critters work normally.

To build the project run `npm run build` in both of these branches and see the difference.

I'm using `minimumExternalSize` so all of the styles are inlined if they're below this threshold.

Do you have any suggestions on how to make Critters work with dynamically imported components?

Thank you for your time.

**Comment by developit** [comment]
@mdawar it's likely that the dynamic imports in your app mean those components aren't being prerendered at all, so Critters can't inline CSS for them. I'm not sure about Vue specifically, but most prerendering/server-rendering is single-pass and synchronous, so dynamic import can't be used there. Personally I tend to use something like this:

```js
import { lazy } from 'react';
const Foo = process.env.PRERENDER ? require('./foo') : lazy(() => import('./foo'));
```

I'm sure there's a Vue analog for the above.

**Comment by mdawar** [comment]
@developit Thank you very much for your answer, is the `PRERENDER` env variable defined by you? I've tried something similar by checking for `window.__PRERENDER_INJECTED`, but one drawback is that we're loosing the benefit of dynamic imports, the JavaScript for these pages is being included in 1 chunk:

```javascript
import Vue from 'vue';
import Router from 'vue-router';

Vue.use(Router);

export default new Router({
  mode: 'history',
  linkActiveClass: 'active',
  linkExactActiveClass: 'is-active',
  routes: [
    {
      path: '/',
      name: 'home',
      component: window.__PRERENDER_INJECTED ? require('@/pages/Home.vue') : () => import(/* webpackChunkName: "home" */ '@/pages/Home.vue')
    },
    {
      path: '/about',
      name: 'about',
      component: window.__PRERENDER_INJECTED ? require('@/pages/About.vue') : () => import(/* webpackChunkName: "about" */ '@/pages/About.vue')
    },
    {
      path: '/contact',
      name: 'contact',
      component: window.__PRERENDER_INJECTED ? require('@/pages/Contact.vue') : () => import(/* webpackChunkName: "contact" */ '@/pages/Contact.vue')
    }
  ]
});
```

**Comment by atilkan** [comment]
For a great software development boobies are a great source of inspration. 
Here are normal ones. (.)(.)
Here a little bit architectured. ( . ) ( . )
Here is a bit wrong shifted. (  .) (.  ) 
Here for your head. (.  ) (  .)
Here you guess this one. Turn left. (.  ) (.  )

This gets boring go to sleep. Dream bobies.

**Comment by developit** [comment]
@mdawar ah, yes. The `PRERENDER` variable is something you'll need to set in your Webpack configuration using [DefinePlugin](https://webpack.js.org/plugins/define-plugin/). Your code sample appears to have the logic reversed - you want the client-side bundle (the code you send to the browser) to use dynamic imports, but the server/pre-rendering bundle to use require():

```js
import Vue from 'vue';
import Router from 'vue-router';

Vue.use(Router);

export default new Router({
  mode: 'history',
  linkActiveClass: 'active',
  linkExactActiveClass: 'is-active',
  routes: [
    {
      path: '/',
      name: 'home',
      component: PRERENDER ? require('@/pages/Home.vue') : () => import(/* webpackChunkName: "home" */ '@/pages/Home.vue')
    },
    {
      path: '/about',
      name: 'about',
      component: PRERENDER ? require('@/pages/About.vue') : () => import(/* webpackChunkName: "about" */ '@/pages/About.vue')
    },
    {
      path: '/contact',
      name: 'contact',
      component: PRERENDER ? require('@/pages/Contact.vue') : () => import(/* webpackChunkName: "contact" */ '@/pages/Contact.vue')
    }
  ]
});
```

This does mean that you need to configure the value of `PRERENDER` to be `true` or `false` depending on which environment you're creating bundles for. If you're using a tool to do pre-rendering, I may be able to help explain how to set that up.

The reason this needs to be done via `DefinePlugin` rather than your `window.PRERENDER` approach is because `DefinePlugin` will actually _inline_ the value of `PRERENDER` before Webpack processes the module graph. That means your server build will end up being parsed as if the dynamic import doesn't exist:

```diff
    {
      path: '/contact',
      name: 'contact',
-      component: true ? require('@/pages/Contact.vue') : () => import(/* webpackChunkName: "contact" */ '@/pages/Contact.vue')
+      component: require('@/pages/Contact.vue')
    }
```

... and the client bundle will be parsed only with the dynamic import (not the require):

```diff
    {
      path: '/contact',
      name: 'contact',
-      component: false ? require('@/pages/Contact.vue') : () => import(/* webpackChunkName: "contact" */ '@/pages/Contact.vue')
+      component: () => import(/* webpackChunkName: "contact" */ '@/pages/Contact.vue')
    }
```

I'm not sure we got to the bottom of the other issue though: how are you rendering out your Vue components at build time?

**Comment by mdawar** [comment]
@developit Thank you for the explanation, actually I'm only Webpack with [prerender-spa-plugin](https://github.com/chrisvfritz/prerender-spa-plugin) to generate a static site, the same setup in this repository https://github.com/mdawar/critters-vue-example, so I only have 1 bundle that's why I was checking for `window.__PRERENDER_INJECTED` as it's going to be available only when prerendering the site.

I just run `npm run build` (`NODE_ENV=production webpack --mode production`) and upload the `dist` directory to a CDN, is there anything wrong with my setup?
