### ISSUE TITLE
Strategy `media` is loading CSS at highest priority

### ISSUE THREAD

**Issue by prateekbh** [GoogleChromeLabs/critters#59]
With strategy `media`, the actual file is still loaded with the highest priority.
This defeats the purpose of the inline styles as the actual CSS file might not be render blocking but is still in Network contention with the rest of the resources.
This makes other resources like images/fonts which are critical for FCP/LCP etc to come later than expected.

A better option would be to use `media=print` which forces this priority to go down to lowest, opening up the network to other more important resources.

**Comment by developit** [comment]
Just merged #39 which should fix this.
