### ISSUE TITLE
DTS feedback

### ISSUE THREAD

**Issue by alan-agius4** [GoogleChromeLabs/critters#66]
- `logLevel?: string` is too permissive and should be changed to something along `logLevel?: 'warn' | 'log' | 'info' | 'error'`.
- `logger` is not exposed as part of the options 
- the interface `Options` is not exported. It would be nice to have these exported accessing the options interface as such:
```ts
import Critters, { Options } from 'critters';
```

**Comment by janicklas-ralph** [comment]
`logLevel` isn't being used in the non-webpack version
`logger` can be overridden by passing a logger through options. The default one just uses the console methods, but I assume users would want more control of their logging

I am not sure what you mean by `the interface Options is not exported`?
If you are referring to the options that Critters uses, everything is taken from the options passed to the constructor.

**Comment by alan-agius4** [comment]
Yeah, it would be great if users can provide their own logger.

Re the `Options` interface, this is currently not exported, ie, it’s defined without the `export` keyword. This means that uses cannot import and use the interface directly.  Which means that users will rely on type inference.

Example users currently are not able to do something like:

```ts
import Critters, { Options } from 'critters';
const opt: Options = {ssrMode: false};
const c = new Critters(opt);
```

But need to rely on inference.
```ts
import Critters from 'critters';
const opt = {ssrMode: false};
const c = new Critters(opt);
```

The above is simple version of the use-case were the `Options` interface would be useful to be exported.
