### ISSUE TITLE
unmatched pseudo-class :is

### ISSUE THREAD

**Issue by heyitsarpit** [GoogleChromeLabs/critters#79]
Currently using critters in nextjs looks like it can't handle psuedoclasses.

Error - 
3 rules skipped due to selector errors:
  article :is(h1,h2,h3,h4,h5,h6) -> unmatched pseudo-class :is
  .dark article :is(h1,.dark h2,.dark h3,.dark h4,.dark h5,.dark h6) -> unmatched pseudo-class :is
  article :is(h2,h3,h4,h6) .anchor -> unmatched pseudo-class :is

**Comment by developit** [comment]
This may be fixed by #80 or #82.

**Comment by developit** [comment]
Please re-open if this is still happening in the latest critters.
