### ISSUE TITLE
Don't load rest of styles

### ISSUE THREAD

**Issue by woophi** [GoogleChromeLabs/critters#92]
I use critters 0.0.15 and next 12.0.7. and it looks like the rest of styles couldn't load at all.

What are possible reasons why does it happen?

![image](https://user-images.githubusercontent.com/23319212/145355729-dd76e1c6-d4f9-40a5-a7c6-111779f2164f.png)

**Comment by janicklas-ralph** [comment]
Thats a different tag used internally by NextJS. Can you see inline styles loaded further down? It would be helpful to share a link to the repo or the site.

**Comment by woophi** [comment]
I can't share repo, cause it's private. 

Luckily I found a problem that caused block of loading styles. In custom server I have a helmet with csp rule. that's why `media="print"` never changes.
